services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: battery

  redis:
    image: redis:7-alpine
    container_name: battery_redis
    ports:
      - "6379:6379"

  backend_api:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    environment:
      - DB_DSN=postgresql://postgres:postgres@timescaledb:5432/battery
      - REDIS_URL=redis://redis:6379/0
      - ML_SERVICE_URL=http://ml_service:8002
      - ENTSOE_API_KEY=${ENTSOE_API_KEY}
    depends_on:
      - timescaledb
      - redis
      - ml_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  backend_worker:
    build: ./backend
    container_name: backend_worker
    command: celery -A worker.celery_app worker --loglevel=info
    environment:
      - DB_DSN=postgresql://postgres:postgres@timescaledb:5432/battery
      - REDIS_URL=redis://redis:6379/0
      - ML_SERVICE_URL=http://ml_service:8002
      - ENTSOE_API_KEY=${ENTSOE_API_KEY}
    depends_on:
      - timescaledb
      - redis
      - backend_api

  ml_service:
    build: ./ml_service
    container_name: ml_service
    ports:
      - "8002:8002"
    environment:
      - BENTOML_HOME=/app/ml_service/data/bentoml
    volumes:
      - ./ml_service/data:/app/ml_service/data

  frontend:
    build: ./frontend
    container_name: battery_frontend
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend_api
